### ISSUE TITLE
Project Description?

### ISSUE THREAD

**Issue by darth-cheney** [seandenigris/Computer-World#6]
Hi Sean,

Just came across this project on Github and from what I can piece together it looks very interesting. Do you have a short, concrete description of what you are trying to accomplish and current capabilities? Thanks!

**Comment by seandenigris** [comment]
> Do you have a short, concrete description of what you are trying to accomplish

Updated the [first section of the readme](https://github.com/seandenigris/Computer-World#computer-world). Let me know if that helps.

> and current capabilities?
Since these projects are all personal things that I open sourced just recently, unfortunately there's not much coordinated documentation. Since it's made on GT, there are examples in image. I'm happy to answer questions and I'm working on documenting better.

**Comment by seandenigris** [comment]
I'll close for now and reopen if needed if @darth-cheney replies.

**Comment by darth-cheney** [comment]
Sorry for not responding sooner @seandenigris . I'm all set here and I get the idea now!
